# Generated by Django 3.1.3 on 2020-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20201122_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='CompanyId',
            field=models.IntegerField(null=True),
        ),
    ]
