# Generated by Django 3.1.3 on 2020-11-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_users_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='User',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Company',
        ),
        migrations.AddField(
            model_name='userroles',
            name='RoleId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='UserId',
            field=models.IntegerField(null=True),
        ),
    ]
